/**
 * Category alias maps for import/merge: normalized names → canonical names.
 * Extensible: add locale/region-specific overrides by implementing CategoryAliasProvider.
 */

/** Top-level category: alias (normalized) → canonical normalized name. */
export const TOP_LEVEL_ALIASES: Readonly<Record<string, string>> = {
  food: "food dining",
  dining: "food dining",
  "food and dining": "food dining",
  groceries: "food dining",
  shopping: "shopping",
  apparel: "shopping",
  clothing: "shopping",
  accessories: "shopping",
  fashion: "shopping",
  transport: "transportation",
  transportations: "transportation",
  entertainment: "entertainment",
  bills: "bills utilities",
  utilities: "bills utilities",
  "bills and utilities": "bills utilities",
  health: "health fitness",
  fitness: "health fitness",
  healthcare: "health fitness",
  medical: "health fitness",
  travel: "travel",
  trips: "travel",
  education: "education",
  personal: "personal care",
  "personal care": "personal care",
  beauty: "personal care",
  donation: "gifts donations",
  donations: "gifts donations",
  gift: "gifts donations",
  gifts: "gifts donations",
  charity: "gifts donations",
  "gifts and donations": "gifts donations",
  "gifts donations": "gifts donations",
  pets: "pets",
  kids: "kids family",
  family: "kids family",
  "kids and family": "kids family",
  "kids family": "kids family",
  "home maintenance": "home maintenance",
  maintenance: "home maintenance",
  home: "home maintenance",
  household: "household",
  loans: "loans emi",
  loan: "loans emi",
  emi: "loans emi",
  "loans and emi": "loans emi",
  "loans emi": "loans emi",
  taxes: "taxes",
  tax: "taxes",
  cash: "cash atm",
  atm: "cash atm",
  "cash and atm": "cash atm",
  "cash atm": "cash atm",
  festivals: "festivals occasions",
  occasions: "festivals occasions",
  "festivals and occasions": "festivals occasions",
  "festivals occasions": "festivals occasions",
  subscription: "subscriptions",
  subscriptions: "subscriptions",
  rent: "rent",
  "self development": "self development",
  "self-development": "self development",
  selfdevelopment: "self development",
  other: "other",
  others: "other",
  salary: "salary",
  freelance: "freelance",
  freelancing: "freelance",
  investments: "investments",
  investment: "investments",
  "rental income": "rental income",
  rental: "rental income",
  "side hustle": "side hustle",
  sidehustle: "side hustle",
  "cashback and rewards": "cashback rewards",
  "cashback rewards": "cashback rewards",
  cashback: "cashback rewards",
  rewards: "cashback rewards",
  "government benefits": "government benefits",
  government: "government benefits",
  "gifts received": "gifts received",
  "gift received": "gifts received",
  refunds: "refunds",
  refund: "refunds",
  "sale of items": "sale of items",
  sale: "sale of items",
  "other income": "other",
} as const;

/** Subcategory: alias (normalized) → list of canonical sub norm names to try. */
export const SUB_ALIASES: Readonly<Record<string, readonly string[]>> = {
  donation: ["religious donations", "charity"],
  donations: ["religious donations", "charity"],
  religious: ["religious donations"],
  "religious donations": ["religious donations"],
  charity: ["charity"],
  tips: ["tips"],
  flight: ["flights"],
  flights: ["flights"],
  hotel: ["hotels"],
  hotels: ["hotels"],
  vacation: ["vacation"],
  sightseeing: ["sightseeing"],
  grocery: ["groceries"],
  groceries: ["groceries"],
  restaurant: ["restaurants"],
  restaurants: ["restaurants"],
  "coffee and drinks": ["coffee drinks"],
  coffee: ["coffee drinks"],
  drinks: ["coffee drinks"],
  takeout: ["takeout"],
  "food delivery": ["food delivery"],
  "eating out": ["eating out"],
  fuel: ["fuel"],
  parking: ["parking"],
  taxi: ["taxi uber"],
  uber: ["taxi uber"],
  "public transport": ["public transport"],
  bus: ["bus"],
  "subway metro": ["subway metro"],
  subway: ["subway metro"],
  metro: ["subway metro"],
  maintenance: ["maintenance"],
  car: ["car"],
  toll: ["toll"],
  "car wash": ["car wash"],
  "car insurance": ["car insurance"],
  repairs: ["repairs"],
  rentals: ["rentals"],
  "fines and challans": ["fines challans"],
  "fines challans": ["fines challans"],
  movies: ["movies"],
  games: ["games"],
  "music and concerts": ["music concerts"],
  music: ["music concerts"],
  sports: ["sports"],
  streaming: ["streaming"],
  "streaming services": ["streaming services"],
  hobbies: ["hobbies"],
  "events and tickets": ["events tickets"],
  events: ["events tickets"],
  electricity: ["electricity"],
  water: ["water"],
  internet: ["internet"],
  phone: ["phone"],
  rent: ["rent"],
  insurance: ["insurance"],
  gas: ["gas"],
  "waste garbage": ["waste garbage"],
  garbage: ["waste garbage"],
  "security alarm": ["security alarm"],
  "bank fees": ["bank fees"],
  "credit card fees": ["credit card fees"],
  "cable tv": ["cable tv"],
  gym: ["gym"],
  medicine: ["medicine"],
  doctor: ["doctor"],
  supplements: ["supplements"],
  hospital: ["hospital"],
  dental: ["dental"],
  "vision eye care": ["vision eye care"],
  "health insurance": ["health insurance"],
  "life insurance": ["life insurance"],
  tests: ["tests"],
  devices: ["devices"],
  clothing: ["clothing"],
  clothes: ["clothing"],
  apparel: ["clothing"],
  wear: ["clothing"],
  electronics: ["electronics"],
  "home and garden": ["home garden"],
  "home garden": ["home garden"],
  accessories: ["accessories"],
  "online shopping": ["online shopping"],
  "jewelry and gold": ["jewelry gold"],
  "jewelry gold": ["jewelry gold"],
  "buying gifts": ["buying gifts"],
  stationery: ["stationery"],
  fashion: ["fashion"],
  tailor: ["tailor"],
  ornaments: ["ornaments"],
  courses: ["courses"],
  books: ["books"],
  tuition: ["tuition"],
  "exam fees": ["exam fees"],
  haircut: ["haircut"],
  skincare: ["skincare"],
  "spa and wellness": ["spa wellness"],
  spa: ["spa wellness"],
  cosmetics: ["cosmetics"],
  makeup: ["makeup"],
  "beauty accessories": ["beauty accessories"],
  "pet food": ["pet food"],
  "vet medical": ["vet medical"],
  vet: ["vet medical"],
  grooming: ["grooming"],
  "pet supplies": ["pet supplies"],
  "pet insurance": ["pet insurance"],
  "childcare daycare": ["childcare daycare"],
  childcare: ["childcare daycare"],
  daycare: ["childcare daycare"],
  "school fees": ["school fees"],
  "tuition coaching": ["tuition coaching"],
  coaching: ["tuition coaching"],
  "kids activities": ["kids activities"],
  "baby products": ["baby products"],
  "kids clothing": ["kids clothing"],
  toys: ["toys"],
  "allowance pocket money": ["allowance pocket money"],
  allowance: ["allowance pocket money"],
  "pocket money": ["allowance pocket money"],
  "kids medical": ["kids medical"],
  "children medical": ["kids medical"],
  decor: ["decor"],
  appliances: ["appliances"],
  furnishing: ["furnishing"],
  "cleaning services": ["cleaning services"],
  "house help": ["house help"],
  "helping hand": ["house help"],
  cook: ["house help"],
  maid: ["house help"],
  maids: ["house help"],
  "domestic help": ["house help"],
  "household help": ["house help"],
  servant: ["house help"],
  "domestic worker": ["house help"],
  "home improvement": ["home improvement"],
  furniture: ["furniture"],
  gardening: ["gardening"],
  "home loan emi": ["home loan emi"],
  "car loan emi": ["car loan emi"],
  "personal loan emi": ["personal loan emi"],
  "education loan emi": ["education loan emi"],
  "credit card payment": ["credit card payment"],
  "loan interest": ["loan interest"],
  "income tax": ["income tax"],
  "property tax": ["property tax"],
  "gst sales tax": ["gst sales tax"],
  "other taxes": ["other taxes"],
  "toll tax": ["toll tax"],
  "cash withdrawal": ["cash withdrawal"],
  "cash expense": ["cash expense"],
  diwali: ["diwali"],
  holi: ["holi"],
  christmas: ["christmas"],
  eid: ["eid"],
  birthday: ["birthday"],
  anniversary: ["anniversary"],
  wedding: ["wedding"],
  "monthly salary": ["monthly salary"],
  bonus: ["bonus"],
  overtime: ["overtime"],
  hra: ["hra"],
  "travel allowance": ["travel allowance"],
  "other allowances": ["other allowances"],
  "project payment": ["project payment"],
  consulting: ["consulting"],
  commission: ["commission"],
  dividends: ["dividends"],
  interest: ["interest"],
  "capital gains": ["capital gains"],
  "mutual funds": ["mutual funds"],
  stocks: ["stocks"],
  "property rent": ["property rent"],
  "room rent": ["room rent"],
  "parking rent": ["parking rent"],
  flat: ["flat"],
} as const;

/** Provider for alias maps; implement for locale/region or A/B overrides. */
export interface CategoryAliasProvider {
  getTopLevelAliases(): Readonly<Record<string, string>>;
  getSubAliases(): Readonly<Record<string, readonly string[]>>;
}

const defaultProvider: CategoryAliasProvider = {
  getTopLevelAliases: () => TOP_LEVEL_ALIASES,
  getSubAliases: () => SUB_ALIASES,
};

/** Default alias provider (single locale). Replace or wrap for future extensions. */
export function getDefaultCategoryAliasProvider(): CategoryAliasProvider {
  return defaultProvider;
}
